indexJson:
  path: /Json # /{nom}
  controller: App\Controller\JsonController::receptionContrat

indexJsonVar:
  path: /JsonVar/{id}
  controller: App\Controller\JsonController::envoiVar

indexPdf:
  path: /Pdf
  controller: App\Controller\PdfController::generatePdf

indexHtml:
  path: /Html
  controller: App\Controller\HtmlController::generateHtml
